### STAGE 1 : Build the go source code into binary
FROM golang:latest as builder

ENV APP_DIR /stockplay

## Copy source code from local machine into container
RUN mkdir -p ${APP_DIR}
COPY . ${APP_DIR}

# Compile the binary and statically link
RUN cd $APP_DIR && CGO_ENABLED=0 go build -o encryptor -ldflags '-d -w -s' cmd/encryptor/main.go

### STAGE 2 : Package the binary in a minimal alpine base image
FROM alpine:latest

ENV APP_DIR /stockplay

COPY --from=builder ${APP_DIR}/encryptor .

RUN apk add curl tzdata ca-certificates

CMD ["./encryptor"]





